# Generated by Django 2.2.18 on 2021-02-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Note',
            name='priority',
            field=models.TextField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6),
            preserve_default=False,
        ),
    ]
